"""
fix_acentos.py — Corrige acentuação e pontuação nos 30 MDX da Fase 1.
Aplica substituições word-boundary preservando capitalização.
"""
import sys, os, re
sys.stdout.reconfigure(encoding='utf-8')

BLOG_DIR = r"D:\ia\Projeto Ahara\src\content\blog"

SLUGS = [
    'batata-chips-revenda-go','batata-chips-revender-go','batata-chips-atacado-go',
    'batata-chips-revenda-mg','batata-chips-revender-mg','batata-chips-atacado-mg',
    'batata-chips-revenda-sp','batata-chips-revender-sp','batata-chips-atacado-sp',
    'batata-chips-revenda-rj','batata-chips-revender-rj','batata-chips-atacado-rj',
    'batata-chips-revenda-pr','batata-chips-revender-pr','batata-chips-atacado-pr',
    'batata-chips-revenda-rs','batata-chips-revender-rs','batata-chips-atacado-rs',
    'batata-chips-revenda-ba','batata-chips-revender-ba','batata-chips-atacado-ba',
    'batata-chips-revenda-pe','batata-chips-revender-pe','batata-chips-atacado-pe',
    'batata-chips-revenda-ce','batata-chips-revender-ce','batata-chips-atacado-ce',
    'batata-chips-revenda-sc','batata-chips-revender-sc','batata-chips-atacado-sc',
]

# Dicionário: chave=sem acento (lowercase), valor=com acento correto
# Ordenar do maior para menor para evitar substituições parciais
CORRECOES = {
    # ── Geográficos ─────────────────────────────────────────────────────────
    'goias':            'Goiás',
    'goiania':          'Goiânia',
    'goiano':           'goiano',
    'goiana':           'goiana',
    'goianos':          'goianos',
    'goianas':          'goianas',
    'parana':           'Paraná',
    'paranaense':       'paranaense',
    'paranaenses':      'paranaenses',
    'ceara':            'Ceará',
    'cearense':         'cearense',
    'cearenses':        'cearenses',
    'brasilia':         'Brasília',
    'florianopolis':    'Florianópolis',
    'floripa':          'Floripa',
    'uberlandia':       'Uberlândia',
    'anapolis':         'Anápolis',
    'londrina':         'Londrina',
    'maringa':          'Maringá',
    'joinville':        'Joinville',
    'blumenau':         'Blumenau',
    'camboriu':         'Camboriú',
    'itapema':          'Itapema',
    'balnearios':       'balneários',
    # ── -ão / -ões ──────────────────────────────────────────────────────────
    'nao':              'não',
    'sao':              'são',
    'tambem':           'também',
    'apos':             'após',
    'entao':            'então',
    'porem':            'porém',
    'alem':             'além',
    'ainda':            'ainda',
    'alem':             'além',
    'tao':              'tão',
    'producao':         'produção',
    'distribuicao':     'distribuição',
    'reposicao':        'reposição',
    'negociacao':       'negociação',
    'avaliacao':        'avaliação',
    'operacao':         'operação',
    'operacoes':        'operações',
    'selecao':          'seleção',
    'selecoes':         'seleções',
    'reducao':          'redução',
    'reducoes':         'reduções',
    'situacao':         'situação',
    'situacoes':        'situações',
    'informacao':       'informação',
    'informacoes':      'informações',
    'condicao':         'condição',
    'condicoes':        'condições',
    'posicao':          'posição',
    'posicoes':         'posições',
    'versao':           'versão',
    'versoes':          'versões',
    'visao':            'visão',
    'visoes':           'visões',
    'regiao':           'região',
    'regioes':          'regiões',
    'secao':            'seção',
    'secoes':           'seções',
    'gestao':           'gestão',
    'gestoes':          'gestões',
    'questao':          'questão',
    'questoes':         'questões',
    'atencao':          'atenção',
    'atencoes':         'atenções',
    'formacao':         'formação',
    'aplicacao':        'aplicação',
    'aplicacoes':       'aplicações',
    'comunicacao':      'comunicação',
    'organizacao':      'organização',
    'solucao':          'solução',
    'solucoes':         'soluções',
    'opcao':            'opção',
    'opcoes':           'opções',
    'acao':             'ação',
    'acoes':            'ações',
    'relacao':          'relação',
    'relacoes':         'relações',
    'funcao':           'função',
    'funcoes':          'funções',
    'expansao':         'expansão',
    'conversao':        'conversão',
    'adaptacao':        'adaptação',
    'aquisicao':        'aquisição',
    'absorcao':         'absorção',
    'aceitacao':        'aceitação',
    'adequacao':        'adequação',
    'adesao':           'adesão',
    'adicao':           'adição',
    'aprovacao':        'aprovação',
    'atuacao':          'atuação',
    'circulacao':       'circulação',
    'coloracao':        'coloração',
    'combinacao':       'combinação',
    'composicao':       'composição',
    'concentracao':     'concentração',
    'confirmacao':      'confirmação',
    'conservacao':      'conservação',
    'consolidacao':     'consolidação',
    'contribuicao':     'contribuição',
    'cotacao':          'cotação',
    'decisao':          'decisão',
    'decisoes':         'decisões',
    'definicao':        'definição',
    'degradacao':       'degradação',
    'degustacao':       'degustação',
    'devolucao':        'devolução',
    'devolucoes':       'devoluções',
    'diferenciacao':    'diferenciação',
    'documentacao':     'documentação',
    'emissao':          'emissão',
    'equacao':          'equação',
    'estruturacao':     'estruturação',
    'evolucao':         'evolução',
    'exigencia':        'exigência',
    'exigencias':       'exigências',
    'expansao':         'expansão',
    'exposicao':        'exposição',
    'fidelizacao':      'fidelização',
    'fragmentacao':     'fragmentação',
    'identificacao':    'identificação',
    'importacao':       'importação',
    'incidencia':       'incidência',
    'inflexao':         'inflexão',
    'localizacao':      'localização',
    'negociacao':       'negociação',
    'obrigacoes':       'obrigações',
    'orientacao':       'orientação',
    'orientacoes':      'orientações',
    'padronizacao':     'padronização',
    'percepcao':        'percepção',
    'precificacao':     'precificação',
    'precisao':         'precisão',
    'programacao':      'programação',
    'protecao':         'proteção',
    'razao':            'razão',
    'razoes':           'razões',
    'reabastecimento':  'reabastecimento',
    'recepcao':         'recepção',
    'reclamacoes':      'reclamações',
    'reputacao':        'reputação',
    'restricao':        'restrição',
    'restricoes':       'restrições',
    'rotacao':          'rotação',
    'segmentacao':      'segmentação',
    'separacao':        'separação',
    'simulacao':        'simulação',
    'tensao':           'tensão',
    'variacao':         'variação',
    'variacoes':        'variações',
    'ventilacao':       'ventilação',
    'verificacao':      'verificação',
    'balcao':           'balcão',
    'balcoes':          'balcões',
    'porcao':           'porção',
    'porcoes':          'porções',
    'combinacoes':      'combinações',
    'sensacoes':        'sensações',
    'proporcoes':       'proporções',
    'obrigacoes':       'obrigações',
    'sertao':           'sertão',
    'reconcavo':        'Recôncavo',
    'triangulo':        'triângulo',
    # ── -ência / -ância ─────────────────────────────────────────────────────
    'crocancia':        'crocância',
    'consistencia':     'consistência',
    'frequencia':       'frequência',
    'frequente':        'frequente',
    'frequentes':       'frequentes',
    'frequentemente':   'frequentemente',
    'experiencia':      'experiência',
    'eficiencia':       'eficiência',
    'eficacia':         'eficácia',
    'concorrencia':     'concorrência',
    'referencia':       'referência',
    'referencias':      'referências',
    'excelencia':       'excelência',
    'inteligencia':     'inteligência',
    'emergencia':       'emergência',
    'urgencia':         'urgência',
    'agencia':          'agência',
    'residencia':       'residência',
    'sequencia':        'sequência',
    'sequencias':       'sequências',
    'preferencia':      'preferência',
    'preferencias':     'preferências',
    'suficiencia':      'suficiência',
    'aparencia':        'aparência',
    'ausencia':         'ausência',
    'aderencia':        'aderência',
    'antecedencia':     'antecedência',
    'conferencia':      'conferência',
    'confianca':        'confiança',
    'conveniencia':     'conveniência',
    'conveniencias':    'conveniências',
    'distancia':        'distância',
    'diferenca':        'diferença',
    'diferencas':       'diferenças',
    'existencia':       'existência',
    'higroscopicidade': 'higroscopicidade',
    'importancia':      'importância',
    'incidencia':       'incidência',
    'independencia':    'independência',
    'influencia':       'influência',
    'recorrencia':      'recorrência',
    'resistencia':      'resistência',
    'seguranca':        'segurança',
    'sustentancia':     'sustentância',
    'tolerancia':       'tolerância',
    'transparencia':    'transparência',
    'vigencia':         'vigência',
    'longevidade':      'longevidade',
    # ── Paroxítonas com acento na antepenúltima ──────────────────────────────
    'minimo':           'mínimo',
    'minima':           'mínima',
    'minimos':          'mínimos',
    'minimas':          'mínimas',
    'maximo':           'máximo',
    'maxima':           'máxima',
    'maximos':          'máximos',
    'maximas':          'máximas',
    'critico':          'crítico',
    'critica':          'crítica',
    'criticos':         'críticos',
    'criticas':         'críticas',
    'criterio':         'critério',
    'criterios':        'critérios',
    'especifico':       'específico',
    'especifica':       'específica',
    'especificos':      'específicos',
    'especificas':      'específicas',
    'especificamente':  'especificamente',
    'tecnico':          'técnico',
    'tecnica':          'técnica',
    'tecnicos':         'técnicos',
    'tecnicas':         'técnicas',
    'tipico':           'típico',
    'tipica':           'típica',
    'tipicos':          'típicos',
    'tipicas':          'típicas',
    'logistica':        'logística',
    'logistico':        'logístico',
    'logisticas':       'logísticas',
    'logisticos':       'logísticos',
    'logica':           'lógica',
    'logico':           'lógico',
    'organico':         'orgânico',
    'organica':         'orgânica',
    'organicos':        'orgânicos',
    'organicas':        'orgânicas',
    'automatico':       'automático',
    'automatica':       'automática',
    'automaticamente':  'automaticamente',
    'basico':           'básico',
    'basica':           'básica',
    'basicos':          'básicos',
    'basicas':          'básicas',
    'classico':         'clássico',
    'classica':         'clássica',
    'classicos':        'clássicos',
    'classicas':        'clássicas',
    'estetico':         'estético',
    'estetica':         'estética',
    'esteticos':        'estéticos',
    'esteticas':        'estéticas',
    'plastico':         'plástico',
    'plastica':         'plástica',
    'plasticos':        'plásticos',
    'plasticas':        'plásticas',
    'publico':          'público',
    'publica':          'pública',
    'publicos':         'públicos',
    'publicas':         'públicas',
    'juridico':         'jurídico',
    'juridica':         'jurídica',
    'juridicos':        'jurídicos',
    'juridicas':        'jurídicas',
    'fisico':           'físico',
    'fisica':           'física',
    'fisicos':          'físicos',
    'fisicas':          'físicas',
    'historico':        'histórico',
    'historica':        'histórica',
    'historicos':       'históricos',
    'historicas':       'históricas',
    'economico':        'econômico',
    'economica':        'econômica',
    'economicos':       'econômicos',
    'economicas':       'econômicas',
    'gastronomico':     'gastronômico',
    'gastronomica':     'gastronômica',
    'gastronomicos':    'gastronômicos',
    'gastronomicas':    'gastronômicas',
    'geografico':       'geográfico',
    'geografica':       'geográfica',
    'geograficos':      'geográficos',
    'geograficas':      'geográficas',
    'demografico':      'demográfico',
    'demografica':      'demográfica',
    'demograficos':     'demográficos',
    'demograficas':     'demográficas',
    'turistico':        'turístico',
    'turistica':        'turística',
    'turisticos':       'turísticos',
    'turisticas':       'turísticas',
    'nutricional':      'nutricional',
    'nutricionais':     'nutricionais',
    'sanitario':        'sanitário',
    'sanitaria':        'sanitária',
    'sanitarios':       'sanitários',
    'sanitarias':       'sanitárias',
    'voluntario':       'voluntário',
    'voluntaria':       'voluntária',
    'voluntarios':      'voluntários',
    'voluntarias':      'voluntárias',
    'primario':         'primário',
    'primaria':         'primária',
    'primarios':        'primários',
    'primarias':        'primárias',
    'arbitrario':       'arbitrário',
    'complementario':   'complementário',
    'extraordinario':   'extraordinário',
    'hereditario':      'hereditário',
    'imaginou':         'imaginou',
    'legivel':          'legível',
    'prioritario':      'prioritário',
    'prioritaria':      'prioritária',
    'prioritarios':     'prioritários',
    'prioritarias':     'prioritárias',
    'universitario':    'universitário',
    'universitaria':    'universitária',
    # ── Paroxítonas em -vel ──────────────────────────────────────────────────
    'disponivel':       'disponível',
    'disponiveis':      'disponíveis',
    'acessivel':        'acessível',
    'acessiveis':       'acessíveis',
    'previsivel':       'previsível',
    'previsiveis':      'previsíveis',
    'viavel':           'viável',
    'viaveis':          'viáveis',
    'aplicavel':        'aplicável',
    'aplicaveis':       'aplicáveis',
    'confiaveis':       'confiáveis',
    'confiavel':        'confiável',
    'compativel':       'compatível',
    'compativeis':      'compatíveis',
    'escalavel':        'escalável',
    'escalaveis':       'escaláveis',
    'indispensavel':    'indispensável',
    'indispensaveis':   'indispensáveis',
    'mensuravel':       'mensurável',
    'mensuravelmente':  'mensuravelmente',
    'preferivel':       'preferível',
    'previsiveis':      'previsíveis',
    'rastreavel':       'rastreável',
    'sensiveis':        'sensíveis',
    'sustentavel':      'sustentável',
    'sustentaveis':     'sustentáveis',
    'variavel':         'variável',
    'variaveis':        'variáveis',
    # ── Oxítonas e monossílabos ──────────────────────────────────────────────
    'acucar':           'açúcar',
    'preco':            'preço',
    'precos':           'preços',
    'precificacao':     'precificação',
    'propria':          'própria',
    'proprias':         'próprias',
    'proprio':          'próprio',
    'proprios':         'próprios',
    'proximo':          'próximo',
    'proxima':          'próxima',
    'proximos':         'próximos',
    'proximas':         'próximas',
    'ultimo':           'último',
    'ultima':           'última',
    'ultimos':          'últimos',
    'ultimas':          'últimas',
    'otimo':            'ótimo',
    'otima':            'ótima',
    'otimos':           'ótimos',
    'otimas':           'ótimas',
    'unico':            'único',
    'unica':            'única',
    'unicos':           'únicos',
    'unicas':           'únicas',
    'util':             'útil',
    'uteis':            'úteis',
    'facil':            'fácil',
    'faceis':           'fáceis',
    'dificil':          'difícil',
    'dificeis':         'difíceis',
    'fragil':           'frágil',
    'frageis':          'frágeis',
    'nivel':            'nível',
    'niveis':           'níveis',
    'rapido':           'rápido',
    'rapida':           'rápida',
    'rapidos':          'rápidos',
    'rapidas':          'rápidas',
    'rapido':           'rápido',
    'rapida':           'rápida',
    'imediatamente':    'imediatamente',
    'imediato':         'imediato',
    'padrao':           'padrão',
    'padroes':          'padrões',
    'autonomo':         'autônomo',
    'autonoma':         'autônoma',
    'autonomos':        'autônomos',
    'autonomas':        'autônomas',
    'formulario':       'formulário',
    'formularios':      'formulários',
    'cardapio':         'cardápio',
    'cardapios':        'cardápios',
    'catalogo':         'catálogo',
    'catalogos':        'catálogos',
    'deposito':         'depósito',
    'depositos':        'depósitos',
    'habito':           'hábito',
    'habitos':          'hábitos',
    'indice':           'índice',
    'indices':          'índices',
    'periodo':          'período',
    'periodos':         'períodos',
    'territorio':       'território',
    'territorios':      'territórios',
    'numero':           'número',
    'numeros':          'números',
    'medico':           'médico',
    'medica':           'médica',
    'medicos':          'médicos',
    'medicas':          'médicas',
    'codigo':           'código',
    'codigos':          'códigos',
    'genero':           'gênero',
    'generos':          'gêneros',
    'trafego':          'tráfego',
    'metodo':           'método',
    'metodos':          'métodos',
    'obstaculo':        'obstáculo',
    'obstaculos':       'obstáculos',
    'simbolo':          'símbolo',
    'simbolos':         'símbolos',
    'topicos':          'tópicos',
    'topico':           'tópico',
    # ── Outros sem acento comum ──────────────────────────────────────────────
    'espaco':           'espaço',
    'espacos':          'espaços',
    'comercios':        'comércios',
    'comercio':         'comércio',
    'servico':          'serviço',
    'servicos':         'serviços',
    'endereco':         'endereço',
    'enderecos':        'endereços',
    'veiculo':          'veículo',
    'veiculos':         'veículos',
    'rotulo':           'rótulo',
    'rotulos':          'rótulos',
    'orcamento':        'orçamento',
    'orcamentos':       'orçamentos',
    'liquido':          'líquido',
    'liquida':          'líquida',
    'liquidos':         'líquidos',
    'liquidas':         'líquidas',
    'solido':           'sólido',
    'solida':           'sólida',
    'solidos':          'sólidos',
    'solidas':          'sólidas',
    'valido':           'válido',
    'valida':           'válida',
    'validos':          'válidos',
    'validas':          'válidas',
    'gaucho':           'gaúcho',
    'gaucha':           'gaúcha',
    'gauchos':          'gaúchos',
    'gauchas':          'gaúchas',
    'materia':          'matéria',
    'materias':         'matérias',
    'media':            'média',
    'medias':           'médias',
    'medio':            'médio',
    'medios':           'médios',
    'estrategia':       'estratégia',
    'estrategias':      'estratégias',
    'estrategica':      'estratégica',
    'estrategico':      'estratégico',
    'estrategicas':     'estratégicas',
    'estrategicos':     'estratégicos',
    'categoria':        'categoria',
    'caracteristica':   'característica',
    'caracteristicas':  'características',
    'hermetica':        'hermética',
    'hermeticamente':   'hermeticamente',
    'temperatura':      'temperatura',
    'termica':          'térmica',
    'termicas':         'térmicas',
    'climaticas':       'climáticas',
    'geografica':       'geográfica',
    'especializacao':   'especialização',
    'hipotetico':       'hipotético',
    'hipoteticos':      'hipotéticos',
    'hipotetica':       'hipotética',
    'aereo':            'aéreo',
    'aerea':            'aérea',
    'aereos':           'aéreos',
    'aereas':           'aéreas',
    # ── "é" em padrões específicos (ser/estar) ───────────────────────────────
    # Substituições contextuais de "e" por "é":
    # padrão: " e de " → " é de ", " e o " etc. — muito arriscado geral
    # Faremos apenas padrões seguros específicos:
    # ── Pontuação / ortografia ───────────────────────────────────────────────
    'tres':             'três',
    'voce':             'você',
    'voces':            'vocês',
    'porque':           'porque',
    'tambem':           'também',
    'porem':            'porém',
    'apos':             'após',
    'alem':             'além',
    'entao':            'então',
    'nao':              'não',
    'tao':              'tão',
    'esta':             'está',   # CUIDADO — "esta" = "this" vs "está" = "is"
    'estao':            'estão',
    'serao':            'serão',
    'sao':              'são',
    'vao':              'vão',
    # ── Nordeste específico ──────────────────────────────────────────────────
    'pernambuco':       'Pernambuco',
    'pernambucano':     'pernambucano',
    'pernambucanos':    'pernambucanos',
    'petrolina':        'Petrolina',
    'caruaru':          'Caruaru',
    # ── Sul específico ───────────────────────────────────────────────────────
    'catarinense':      'catarinense',
    'catarinenses':     'catarinenses',
}

# Palavras que NÃO devem ser substituídas em contexto HTML/URL
HTML_SKIP = re.compile(
    r'<[^>]*>|https?://[^\s"\'<>]+|"[^"]*"|\'[^\']*\'',
    re.IGNORECASE
)


def apply_corrections(text: str) -> tuple[str, int]:
    """Aplica correções preservando capitalização e evitando HTML."""
    count = 0

    for wrong, right in CORRECOES.items():
        # Construir padrão case-insensitive com word boundary
        pattern = re.compile(r'\b' + re.escape(wrong) + r'\b', re.IGNORECASE)

        def replace_match(m, right=right):
            original = m.group(0)
            # Preservar capitalização
            if original.isupper():
                return right.upper()
            elif original[0].isupper() and not right[0].isupper():
                return right[0].upper() + right[1:]
            elif original[0].isupper() and right[0].isupper():
                return right
            else:
                return right

        new_text, n = pattern.subn(replace_match, text)
        if n > 0:
            count += n
            text = new_text

    return text, count


# Casos especiais: "e" → "é" em padrões seguros
# Pattern: "X e de Y" / "X e o/a Y" com sujeito + cópula
E_PATTERNS = [
    # " e de " quando precedido de substantivo (não é conjunção)
    (re.compile(r'(\w)\s+e\s+(de\s+\w)', re.IGNORECASE), r'\1 é \2'),
    (re.compile(r'(\w)\s+e\s+(o\s+[A-Z])', re.IGNORECASE), r'\1 é \2'),
    (re.compile(r'(\w)\s+e\s+(a\s+[A-Z])', re.IGNORECASE), r'\1 é \2'),
    # "minimo e" → "mínimo é" (já corrigido o mínimo acima, mas "e" no final)
    (re.compile(r'(aproximadamente\s+R\$\s*[\d,.]+)\.\s+e\s+o\s+', re.IGNORECASE), r'\1. é o '),
]


def process_file(slug: str) -> dict:
    path = os.path.join(BLOG_DIR, slug + '.mdx')
    with open(path, encoding='utf-8') as f:
        original = f.read()

    corrected, n = apply_corrections(original)

    if corrected != original:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(corrected)

    return {'slug': slug, 'changes': n, 'modified': corrected != original}


if __name__ == '__main__':
    print("Corrigindo acentuação nos 30 MDX da Fase 1...\n")
    total = 0
    for slug in SLUGS:
        result = process_file(slug)
        status = f"{result['changes']} correções" if result['modified'] else "sem alterações"
        print(f"  {'✓' if result['modified'] else '·'} {slug}: {status}")
        total += result['changes']
    print(f"\nTotal: {total} correções aplicadas em {len(SLUGS)} arquivos.")
